import {Ionicons} from "@expo/vector-icons";
import {router} from "expo-router";
import {Pressable,ScrollView,StyleSheet,Text,View} from "react-native";
import BottomNav from "../../components/BottomNav";
import {openHomeItemsMarket} from "../lib/externalLinks";
import {useAppLanguage} from "../lib/language";

export default function About(){const {language,text}=useAppLanguage();return <View style={s.page}><ScrollView contentContainerStyle={s.c}>
  <Text style={s.k}>{text("ABOUT FORMAL EXCHANGE","关于 FORMAL EXCHANGE")}</Text>
  <Text style={s.title}>{text("Help eligible Formal tickets reach people who can use them.","让符合资格的人使用原本会被浪费的 Formal 票。")}</Text>
  <Text style={s.lead}>{text("Formal exchange is our main service. Travel tickets, event admissions and airport ride-shares are useful supporting features.","Formal 票交换是我们的主营功能；大巴、火车、活动门票和机场拼车是辅助功能。")}</Text>
  <Pressable style={s.swap} onPress={()=>router.push('/marketplace?filter=swap')}><View style={s.swapIcon}><Ionicons name="swap-horizontal" size={25} color="#fff"/></View><View style={s.flex}><Text style={s.swapTitle}>{text("Ticket Swap · a core way to exchange","换票专区 · 核心交换方式")}</Text><Text style={s.swapText}>{text("Offer an eligible College A ticket for an eligible College B ticket without requiring a cash sale. Any price difference is optional and agreed privately.","可以用符合转让规则的 A 学院票直接交换 B 学院票，不必先进行现金买卖；是否补差价由双方私下决定。")}</Text></View><Ionicons name="chevron-forward" size={20} color="#78350F"/></Pressable>
  <Text style={s.heading}>{text("Why we built it","我们为什么做这个平台")}</Text>
  <View style={s.grid}>
    <Point icon="hourglass-outline" title={text("Formals sell out quickly","Formal 一票难求")}>{text("Formal tickets can be extremely difficult to obtain, including for students at the host college.","Formal 票非常难抢，即使举办学院的本院学生也常常抢不到。")}</Point>
    <Point icon="calendar-outline" title={text("Plans change","计划会变化")}>{text("Someone may secure a ticket and later be unable to attend. Some colleges do not offer refunds or an official resale route.","有人抢到票后临时无法参加，而部分学院不提供退款或官方转售渠道。")}</Point>
    <Point icon="git-compare-outline" title={text("Permitted transfers are fragmented","允许转让的信息很分散")}>{text("Where college rules permit a transfer or name change, spare places and demand are scattered across disconnected groups.","在学院允许转让或更名时，空余名额与需求仍分散在互不相通的群组里。")}</Point>
    <Point icon="people-outline" title={text("Cross-college access is limited","跨学院机会有限")}>{text("Visits to another college—and especially exchanges between Oxford and Cambridge—are rare and hard to discover.","访问其他学院，尤其是牛津与剑桥之间的交流机会很少，也很难发现。")}</Point>
  </View>
  <View style={s.mission}><Text style={s.missionTitle}>{text("What Formal Exchange does","Formal Exchange 的作用")}</Text><Text style={s.missionText}>{text("We bring permitted supply and demand together, make restrictions visible, reduce avoidable waste, and encourage legitimate visits and friendships across colleges and universities.","我们把规则允许的供需集中起来，清晰展示限制，减少可避免的浪费，并促进学院和大学之间合规的访问、交流与友谊。")}</Text></View>
  <View style={s.rule}><Ionicons name="eye-outline" size={24} color="#071B3A"/><View style={s.flex}><Text style={s.ruleTitle}>{text("Why different accounts may see different listings","为什么不同账号看到的帖子可能不同")}</Text><Text style={s.ruleText}>{text("The seller may prioritise host-college members, open the ticket to other Oxford or Cambridge colleges, or—only when college rules permit—open it beyond Oxbridge. Wider visibility is never automatic because host-college students often struggle to obtain their own tickets.","卖家可以优先面向举办学院成员，也可开放给牛津或剑桥其他学院；只有学院规则允许时，才可进一步开放给牛剑以外用户。由于本院学生也常常抢不到票，扩大可见范围并不是自动的。")}</Text></View></View>
  <View style={s.warning}><Ionicons name="warning-outline" size={24} color="#991B1B"/><View style={s.flex}><Text style={s.warningTitle}>{text("College rules always come first","学院规则始终优先")}</Text><Text style={s.warningText}>{text("A prohibited transfer must not be listed or sold. Selling to an ineligible buyer may lead to immediate removal, loss of Formal-listing privileges or account suspension after investigation.","禁止转让的票不得发布或出售。向不符合资格的买家出售，调查属实后可能立即下架、取消 Formal 发布权限或暂停账号。")}</Text></View></View>
  <Text style={s.heading}>{text("Language and automatic translation","语言与自动翻译")}</Text><Text style={s.body}>{text("Your app language is also the language you write in. Write each optional note once; Formal Exchange automatically prepares the other language for readers and keeps a View original option. Machine translations may be imperfect, so eligibility, time, route and price are stored as structured fields wherever possible.","应用界面语言也是你的填写语言。每条可选备注只需写一次；Formal Exchange 会自动为另一种语言的用户生成译文，并保留“查看原文”。机器翻译可能并不完美，因此资格、时间、路线和价格会尽量采用结构化选项保存。")}</Text>
  <Text style={s.heading}>{text("Who can use it?","谁可以使用？")}</Text><Text style={s.body}>{text("Any email may register. Verified .ac.uk staff and students receive community posting permissions; only verified Oxford and Cambridge institutional accounts may publish Formal tickets.","任何邮箱都可注册。已验证的 .ac.uk 学生和教职工可获得社区发布权限；只有已验证的牛津或剑桥机构账号可以发布 Formal 票。")}</Text>
  <Text style={s.heading}>{text("Safety and payments","安全与付款")}</Text><Text style={s.body}>{text("Online payment is unavailable while its safeguards are improved. The platform does not hold funds, guarantee admission or provide automatic refunds. Verify eligibility, evidence, price and transfer rules before paying.","在线付款功能正在完善安全保护，目前不可用。平台不托管资金、不保证入场，也不提供自动退款。付款前请核验资格、凭证、价格和转让规则。")}</Text>
  <Text style={s.heading}>{text("Explore more","了解更多")}</Text><View style={s.actions}><Button label={text("Detailed rules · How it works","详细规则 · 使用方法")} onPress={()=>router.push('/how-it-works')}/><Button label={text("My College Visits","我的学院访问记录")} onPress={()=>router.push('/college-record')}/><Button label={text("College Ratings & Rankings","学院评分与排行")} onPress={()=>router.push('/college-rankings')}/><Button label={text("Second-hand home items (translated)","二手家居用品（liuxuejishi.com）")} onPress={()=>openHomeItemsMarket(language)}/></View>
</ScrollView><BottomNav active="about"/></View>}
function Point({icon,title,children}:{icon:any;title:string;children:any}){return <View style={s.point}><View style={s.icon}><Ionicons name={icon} size={22} color="#fff"/></View><Text style={s.pointTitle}>{title}</Text><Text style={s.pointText}>{children}</Text></View>}
function Button({label,onPress}:{label:string;onPress:()=>void}){return <Pressable style={s.button} onPress={onPress}><Text style={s.buttonText}>{label}</Text><Ionicons name="chevron-forward" size={18} color="#071B3A"/></Pressable>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#F7F4EE'},c:{maxWidth:860,width:'100%',alignSelf:'center',padding:22,paddingTop:38,paddingBottom:110},flex:{flex:1,minWidth:0},k:{fontSize:11,fontWeight:'900',letterSpacing:1.2,color:'#9A3412'},title:{fontSize:38,lineHeight:45,fontWeight:'900',color:'#071B3A',marginTop:8},lead:{fontSize:18,lineHeight:28,fontWeight:'700',color:'#29466F',marginTop:15},swap:{marginTop:18,flexDirection:'row',alignItems:'center',gap:12,backgroundColor:'#FFFBEB',borderWidth:1,borderColor:'#F59E0B',borderRadius:20,padding:16},swapIcon:{width:46,height:46,borderRadius:15,backgroundColor:'#B45309',alignItems:'center',justifyContent:'center'},swapTitle:{fontSize:17,fontWeight:'900',color:'#78350F'},swapText:{color:'#92400E',lineHeight:21,marginTop:5},heading:{fontSize:24,fontWeight:'900',color:'#071B3A',marginTop:30,marginBottom:12},grid:{flexDirection:'row',flexWrap:'wrap',gap:11},point:{width:'48%',minWidth:270,flexGrow:1,backgroundColor:'#fff',borderWidth:1,borderColor:'#E2E8F0',borderRadius:21,padding:17},icon:{width:42,height:42,borderRadius:14,backgroundColor:'#071B3A',alignItems:'center',justifyContent:'center'},pointTitle:{fontSize:17,fontWeight:'900',color:'#071B3A',marginTop:12},pointText:{color:'#64748B',lineHeight:22,marginTop:6},mission:{marginTop:14,backgroundColor:'#071B3A',borderRadius:22,padding:20},missionTitle:{fontSize:20,fontWeight:'900',color:'#D6C7A1'},missionText:{color:'#fff',lineHeight:24,marginTop:8,fontWeight:'700'},rule:{marginTop:22,flexDirection:'row',gap:12,backgroundColor:'#FCF8EA',borderWidth:1,borderColor:'#D6C7A1',borderRadius:20,padding:17},ruleTitle:{fontSize:17,fontWeight:'900',color:'#071B3A'},ruleText:{color:'#475569',lineHeight:22,marginTop:6},warning:{marginTop:11,flexDirection:'row',gap:12,backgroundColor:'#FEF2F2',borderWidth:1,borderColor:'#FCA5A5',borderRadius:20,padding:17},warningTitle:{fontSize:17,fontWeight:'900',color:'#991B1B'},warningText:{color:'#7F1D1D',lineHeight:22,marginTop:6,fontWeight:'700'},body:{color:'#475569',fontSize:15,lineHeight:25},actions:{gap:9},button:{backgroundColor:'#fff',borderWidth:1,borderColor:'#D6C7A1',borderRadius:16,padding:15,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},buttonText:{color:'#071B3A',fontWeight:'900',flex:1}});
