import { Ionicons } from "@expo/vector-icons";
import { router, useLocalSearchParams } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { BuyerPost, getCurrentUser, loadBuyerPosts, openConversation } from "../lib/formalApi";
import { useAppLanguage } from "../lib/language";

const DEMOS=[
  {ticket_type:"Hall Formal",category:"formal",university:"Oxford",wanted_date:"2026-09-08",budget_gbp:30,quantity:1,notes:"Looking for an eligible guest place at an Oxford college. Please state the host college, entry rules, ID requirement and whether host accompaniment is needed."},
  {ticket_type:"MCR Guest Dinner",category:"formal",university:"Cambridge",wanted_date:"2026-09-15",budget_gbp:null,quantity:2,notes:"Two verified Cambridge members looking for an eligible guest allocation. Flexible on college if the seller confirms the transfer rules."},
  {ticket_type:"Train",category:"coach_train",university:"Oxford",wanted_date:"2026-09-18",budget_gbp:22,quantity:1,origin_name:"Oxford",destination_name:"Cambridge",notes:"Flexible after 17:00; railcard-compatible ticket preferred."},
];

export default function BuyerRequestDetail(){
  const {language,text}=useAppLanguage();
  const params=useLocalSearchParams<{id?:string;demo?:string}>(),demo=useMemo(()=>params.demo!==undefined?DEMOS[Number(params.demo)]:null,[params.demo]);
  const [post,setPost]=useState<BuyerPost|null>(null),[loading,setLoading]=useState(Boolean(params.id)),[contacting,setContacting]=useState(false),[showContact,setShowContact]=useState(false),[status,setStatus]=useState("");
  useEffect(()=>{if(!params.id)return;loadBuyerPosts().then(rows=>setPost(rows.find(row=>row.id===params.id)??null)).catch(error=>Alert.alert(text("Could not load request","无法加载需求"),error.message)).finally(()=>setLoading(false));},[params.id]);
  const item=(demo??post) as any;
  const note=demo?(language==="zh"?demoNote(Number(params.demo)):demo.notes):(language==="zh"?(post?.notes_zh??post?.notes):(post?.notes_en??post?.notes));
  async function contact(){try{setContacting(true);setStatus(text("Checking your account…","正在检查账号…"));if(!await getCurrentUser()){router.push("/login");return;}setStatus(text("Opening messages…","正在打开私信…"));const conversation=await openConversation({subject:`${text("Offer to sell","联系出售")} · ${localValue(item.ticket_type,language)}`,sellerUserId:post?.buyer_user_id??null,sellerEmail:demo?"support@formal-exchange.co.uk":post?.buyer_email??"support@formal-exchange.co.uk",isDemo:Boolean(demo)});router.replace(`/messages?conversationId=${conversation.id}`);}catch(error:any){setStatus(`${text("Could not open messages","无法打开私信")}: ${error.message}`);Alert.alert(text("Could not open messages","无法打开私信"),error.message);}finally{setContacting(false);}}
  if(loading)return <View style={s.center}><Text style={s.muted}>{text("Loading request…","正在加载需求…")}</Text></View>;
  if(!item)return <View style={s.center}><Text style={s.title}>{text("Request unavailable","需求不可用")}</Text><Text style={s.muted}>{text("It may have expired or been withdrawn.","需求可能已过期或被撤下。")}</Text><Pressable style={s.primary} onPress={()=>router.replace("/seller")}><Text style={s.primaryText}>{text("Back to requests","返回需求列表")}</Text></Pressable></View>;
  return <ScrollView style={s.page} contentContainerStyle={[s.content,{boxSizing:"border-box"}]}>
    <View style={s.top}><Pressable style={s.icon} onPress={()=>router.canGoBack()?router.back():router.replace("/seller")}><Ionicons name="chevron-back" size={23} color="#071B3A"/></Pressable><Text style={s.topTitle}>{text("Buyer request","买家需求")}</Text><View style={s.icon}/></View>
    {demo?<View style={s.demo}><Text style={s.demoText}>{text("DEMO · This is a sample request. Contact opens a conversation with the Formal Exchange team.","示例 · 这是一条示例需求。点击联系会与 Formal Exchange 团队开始对话。")}</Text></View>:null}
    <View style={s.card}><Text style={s.eyebrow}>{localValue(String(item.category),language)}</Text><Text style={s.title}>{localValue(item.ticket_type,language)}</Text><Text style={s.meta}>{localValue(item.university??"Any city",language)} · {item.wanted_date??text("Flexible date","日期灵活")}</Text><View style={s.priceRow}><Text style={s.price}>{item.budget_gbp?text(`Up to £${Number(item.budget_gbp).toFixed(2)}`,`最高 £${Number(item.budget_gbp).toFixed(2)}`):text("Budget open","预算不限")}</Text><Text style={s.quantity}>{text(`${item.quantity} wanted`,`需要 ${item.quantity} 张`)}</Text></View></View>
    {item.origin_name?<Section title={text("Journey","行程")}><Row icon="navigate-outline" label={text("From","出发地")} value={item.origin_name}/><Row icon="flag-outline" label={text("To","目的地")} value={item.destination_name??text("Flexible","灵活")}/></Section>:null}
    <Section title={text("What the buyer needs","买家需求详情")}><Text style={s.notes}>{note||text("No additional note.","没有补充备注。")}</Text></Section>
    <Section title={text("Contact preference","联系方式偏好")}><Row icon="chatbubble-ellipses-outline" label={text("Preferred","优先方式")} value={localValue(demo?"In-app message":post?.preferred_contact_method??"In-app message",language)}/>{showContact&&!demo&&post?<Row icon="at-outline" label={text("Contact","联系方式")} value={post.contact_value||post.buyer_email}/>:null}<Text style={s.safety}>{text("Use in-app messages first. Confirm the buyer’s eligibility before offering a Formal ticket, and never share passwords or verification codes.","请优先使用应用内私信。提供 Formal 票前请确认买家资格，绝不要分享密码或验证码。")}</Text></Section>
    <Pressable style={({pressed})=>[s.primary,(pressed||contacting)&&s.dim]} disabled={contacting} onPress={contact}><Ionicons name="chatbubble-ellipses-outline" size={20} color="#fff"/><Text style={s.primaryText}>{contacting?text("Opening messages…","正在打开私信…"):text("Contact to sell","联系出售")}</Text></Pressable>
    {status?<Text style={s.status}>{status}</Text>:null}
    {!demo&&post?.contact_value?<Pressable style={s.secondary} onPress={()=>setShowContact(value=>!value)}><Text style={s.secondaryText}>{showContact?text("Hide external contact","隐藏外部联系方式"):text("Show buyer’s chosen contact","显示买家选择的联系方式")}</Text></Pressable>:null}
  </ScrollView>;
}
function localValue(value:string,language:"en"|"zh"){if(language==="en")return value;const map:Record<string,string>={formal:"FORMAL",coach_train:"大巴 / 火车",event:"其他门票 / 拼车","Hall Formal":"学院 Formal","MCR Guest Dinner":"MCR 宾客晚宴",Train:"火车",Coach:"大巴",Oxford:"牛津",Cambridge:"剑桥","Any city":"任意城市","In-app message":"应用内私信",Email:"电子邮件",WeChat:"微信"};return map[value]??value;}
function demoNote(index:number){return ["希望购买一个符合资格的牛津学院宾客名额。请说明举办学院、入场规则、证件要求以及是否需要本院成员陪同。","两名已验证的剑桥成员希望购买符合资格的宾客名额。如卖家确认转让规则，学院选择可以灵活。","17:00 后时间灵活；优先考虑可配合 Railcard 使用的车票。"][index]??""}
function Section({title,children}:{title:string;children:any}){return <View style={s.section}><Text style={s.sectionTitle}>{title}</Text>{children}</View>}
function Row({icon,label,value}:{icon:any;label:string;value:string}){return <View style={s.row}><View style={s.rowIcon}><Ionicons name={icon} size={19} color="#123C69"/></View><View style={s.flex}><Text style={s.rowLabel}>{label}</Text><Text style={s.rowValue}>{value}</Text></View></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:"#F5F1E8"},content:{width:"100%",maxWidth:760,alignSelf:"center",padding:14,paddingBottom:70},center:{flex:1,backgroundColor:"#F5F1E8",alignItems:"center",justifyContent:"center",padding:28},flex:{flex:1,minWidth:0},top:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginBottom:12},icon:{width:42,height:42,borderRadius:21,alignItems:"center",justifyContent:"center",backgroundColor:"#fff"},topTitle:{color:"#071B3A",fontWeight:"900"},demo:{backgroundColor:"#FFFBEB",padding:11,borderRadius:14,marginBottom:10},demoText:{color:"#92400E",fontSize:12,fontWeight:"800",lineHeight:18},card:{backgroundColor:"#fff",borderRadius:22,borderWidth:1,borderColor:"#E2E8F0",padding:18},eyebrow:{color:"#9A3412",fontSize:10,fontWeight:"900",letterSpacing:1,textTransform:"uppercase"},title:{color:"#071B3A",fontSize:27,lineHeight:33,fontWeight:"900",marginTop:5},meta:{color:"#64748B",fontWeight:"700",marginTop:5},priceRow:{flexDirection:"row",justifyContent:"space-between",alignItems:"baseline",gap:10,flexWrap:"wrap",marginTop:15},price:{color:"#9A3412",fontSize:22,fontWeight:"900"},quantity:{color:"#123C69",fontWeight:"900"},section:{backgroundColor:"#fff",borderRadius:22,borderWidth:1,borderColor:"#E2E8F0",padding:17,marginTop:11},sectionTitle:{color:"#071B3A",fontSize:18,fontWeight:"900",marginBottom:6},row:{flexDirection:"row",alignItems:"flex-start",gap:10,paddingVertical:9,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:"#E2E8F0"},rowIcon:{width:34,height:34,borderRadius:17,alignItems:"center",justifyContent:"center",backgroundColor:"#EEF4FA"},rowLabel:{color:"#64748B",fontSize:10,fontWeight:"900",textTransform:"uppercase"},rowValue:{color:"#071B3A",fontWeight:"800",marginTop:2},notes:{color:"#334155",lineHeight:22},safety:{color:"#64748B",fontSize:12,lineHeight:18,marginTop:12},primary:{minHeight:55,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:8,backgroundColor:"#071B3A",borderRadius:17,marginTop:13,paddingHorizontal:17},primaryText:{color:"#fff",fontWeight:"900"},dim:{opacity:.65},status:{color:"#123C69",fontSize:12,fontWeight:"800",textAlign:"center",marginTop:8},secondary:{minHeight:50,alignItems:"center",justifyContent:"center",backgroundColor:"#fff",borderWidth:1,borderColor:"#071B3A",borderRadius:16,marginTop:9},secondaryText:{color:"#071B3A",fontWeight:"900"},muted:{color:"#64748B",textAlign:"center",marginTop:6}});
