import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { College, getCurrentUser, loadColleges, loadMyCollegeVisits, loadMyProfile, setCollegeVisited } from "../lib/formalApi";
import { useAppLanguage } from "../lib/language";

const C={bg:"#F7F4EE",card:"#fff",navy:"#071B3A",blue:"#123C69",muted:"#64748B",border:"#E2E8F0",ok:"#065F46",okBg:"#ECFDF5",red:"#991B1B"};

export default function CollegeRecord(){
  const {text}=useAppLanguage();
  const [colleges,setColleges]=useState<College[]>([]),[visited,setVisited]=useState<Set<string>>(new Set()),[homeCollegeId,setHomeCollegeId]=useState<string|null>(null),[busy,setBusy]=useState<string|null>(null),[status,setStatus]=useState("");
  async function refresh(){if(!await getCurrentUser()){router.replace("/login");return;}const [c,v,p]=await Promise.all([loadColleges(),loadMyCollegeVisits(),loadMyProfile()]);const home=p?.college_id??null;const next=new Set<string>(v.map((x:any)=>x.college_id));if(home)next.add(home);setColleges(c);setHomeCollegeId(home);setVisited(next);}
  useEffect(()=>{refresh().catch(e=>{setStatus(e.message);Alert.alert(text("Could not load record","无法加载访问记录"),e.message);});},[]);
  const remaining=useMemo(()=>colleges.filter(c=>!visited.has(c.id)),[colleges,visited]);
  async function toggle(id:string){if(id===homeCollegeId){setStatus(text("Your profile college is always included automatically.","个人资料中的所属学院会自动计入访问记录。"));return;}try{setBusy(id);setStatus(text("Updating your record…","正在更新访问记录…"));await setCollegeVisited(id,!visited.has(id));await refresh();setStatus(text("Visiting Record updated.","访问记录已更新。"));}catch(e:any){setStatus(e.message);}finally{setBusy(null)}}
  return <ScrollView style={s.page} contentContainerStyle={s.content}>
    <View style={s.topbar}><Pressable style={s.back} onPress={()=>router.canGoBack()?router.back():router.replace("/college-info")}><Ionicons name="chevron-back" size={22} color={C.navy}/></Pressable><View style={s.heading}><Text style={s.kicker}>{text("COLLEGE EXPLORER","学院探索")}</Text><Text style={s.title}>{text("My College Visits","我的学院访问记录")}</Text></View></View>
    <Text style={s.subtitle}>{text("Your profile college is automatically marked as visited. Add colleges after attending a Formal, then rate the experience across five areas.","个人资料中的所属学院会自动标记为已访问。参加其他学院的 Formal 后可在这里记录，并从五个维度评价体验。")}</Text>
    {status?<Text style={s.status}>{status}</Text>:null}
    <View style={s.summary}><View><Text style={s.number}>{visited.size}</Text><Text style={s.caption}>{text("Visited","已访问")}</Text></View><View><Text style={s.number}>{remaining.length}</Text><Text style={s.caption}>{text("Remaining","未访问")}</Text></View><View style={s.progress}><View style={[s.fill,{width:`${colleges.length?visited.size/colleges.length*100:0}%`}]} /></View></View>
    <Text style={s.section}>{text("Visited colleges","已访问学院")}</Text>
    {colleges.filter(c=>visited.has(c.id)).map(c=><VisitedRow key={c.id} c={c} home={c.id===homeCollegeId} busy={busy===c.id} toggle={toggle} text={text}/>)}
    <Text style={s.section}>{text("Remaining colleges","未访问学院")}</Text>
    {remaining.map(c=><RemainingRow key={c.id} c={c} busy={busy===c.id} toggle={toggle} text={text}/>)}
  </ScrollView>;
}

function VisitedRow({c,home,busy,toggle,text}:{c:College;home:boolean;busy:boolean;toggle:(id:string)=>void;text:(en:string,zh:string)=>string}){return <View style={[s.row,s.done]}><View style={s.rowTop}><View style={s.nameCopy}><Text style={s.name}>{c.name}</Text><Text style={s.uni}>{c.university}{home?text(" · Your college"," · 所属学院"):""}</Text></View><Ionicons name="checkmark-circle" size={24} color={C.ok}/></View><View style={s.rowActions}><Pressable style={s.rate} onPress={()=>router.push({pathname:"/college-rating",params:{collegeId:c.id}} as any)}><Ionicons name="star-outline" size={17} color="#fff"/><Text style={s.rateText}>{text("Rate & review","评分与评论")}</Text></Pressable>{!home?<Pressable style={s.remove} disabled={busy} onPress={()=>toggle(c.id)}><Text style={s.removeText}>{busy?text("Saving…","保存中…"):text("Remove visit","移除记录")}</Text></Pressable>:<View style={s.auto}><Text style={s.autoText}>{text("Auto-added","自动计入")}</Text></View>}</View></View>}
function RemainingRow({c,busy,toggle,text}:{c:College;busy:boolean;toggle:(id:string)=>void;text:(en:string,zh:string)=>string}){return <View style={s.row}><View style={s.rowTop}><View style={s.nameCopy}><Text style={s.name}>{c.name}</Text><Text style={s.uni}>{c.university}</Text></View><Pressable style={s.mark} disabled={busy} onPress={()=>toggle(c.id)}><Text style={s.markText}>{busy?text("Saving…","保存中…"):text("Mark visited","标记已访问")}</Text></Pressable></View></View>}

const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg},content:{boxSizing:"border-box",maxWidth:900,width:"100%",alignSelf:"center",padding:18,paddingTop:24,paddingBottom:80},topbar:{flexDirection:"row",alignItems:"center",gap:12},back:{width:44,height:44,borderRadius:15,backgroundColor:C.card,borderWidth:1,borderColor:C.border,alignItems:"center",justifyContent:"center"},heading:{flex:1,minWidth:0},kicker:{color:"#9A3412",fontSize:10,fontWeight:"900",letterSpacing:1},title:{fontSize:29,lineHeight:34,fontWeight:"900",color:C.navy,marginTop:3},subtitle:{marginTop:11,color:C.muted,lineHeight:21},status:{marginTop:12,color:C.blue,fontWeight:"800",fontSize:12},summary:{marginTop:18,backgroundColor:C.card,borderWidth:1,borderColor:C.border,borderRadius:22,padding:17,flexDirection:"row",gap:28,alignItems:"center",flexWrap:"wrap"},number:{fontSize:29,fontWeight:"900",color:C.navy},caption:{color:C.muted,fontSize:11,fontWeight:"800"},progress:{flex:1,minWidth:180,height:11,borderRadius:99,backgroundColor:"#E2E8F0",overflow:"hidden"},fill:{height:"100%",backgroundColor:C.ok},section:{marginTop:22,marginBottom:1,fontSize:20,fontWeight:"900",color:C.navy},row:{marginTop:10,backgroundColor:C.card,borderWidth:1,borderColor:C.border,borderRadius:19,padding:15},done:{backgroundColor:C.okBg},rowTop:{flexDirection:"row",alignItems:"center",gap:10},nameCopy:{flex:1,minWidth:0},name:{color:C.navy,fontWeight:"900",fontSize:16},uni:{marginTop:3,color:C.muted,fontSize:11},rowActions:{flexDirection:"row",flexWrap:"wrap",gap:8,marginTop:12},rate:{minHeight:43,flex:1,minWidth:150,backgroundColor:C.navy,borderRadius:13,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:7,paddingHorizontal:13},rateText:{color:"#fff",fontWeight:"900"},remove:{minHeight:43,borderWidth:1,borderColor:"#FCA5A5",backgroundColor:"#fff",borderRadius:13,alignItems:"center",justifyContent:"center",paddingHorizontal:13},removeText:{color:C.red,fontWeight:"900",fontSize:12},auto:{minHeight:43,borderRadius:13,backgroundColor:"#fff",alignItems:"center",justifyContent:"center",paddingHorizontal:13},autoText:{color:C.ok,fontWeight:"900",fontSize:12},mark:{backgroundColor:C.navy,borderRadius:13,paddingHorizontal:13,paddingVertical:11},markText:{color:"#fff",fontWeight:"900",fontSize:12}});
