import { router } from "expo-router";
import { Ionicons } from "@expo/vector-icons";
import { useEffect,useState } from "react";
import { Alert,Modal,Platform,Pressable,ScrollView,StyleSheet,Text,TextInput,View } from "react-native";
import { TicketListing,completePrivateListingSale,getCurrentUser,loadMyListings,withdrawMyListingSafely } from "../lib/formalApi";
import { useAppLanguage } from "../lib/language";
const C={bg:"#F7F4EE",card:"#fff",navy:"#071B3A",muted:"#64748B",border:"#E2E8F0",danger:"#991B1B",ok:"#065F46",okBg:"#ECFDF5"};

export default function MyListings(){
  const {language,text}=useAppLanguage();
  const [items,setItems]=useState<TicketListing[]>([]),[selected,setSelected]=useState<TicketListing|null>(null),[studentSold,setStudentSold]=useState("0"),[guestSold,setGuestSold]=useState("0"),[busy,setBusy]=useState(false);
  async function refresh(){if(!await getCurrentUser()){router.replace("/login");return;}setItems(await loadMyListings());}
  useEffect(()=>{refresh().catch(e=>Alert.alert(text("Error","错误"),e.message));},[language]);
  function openComplete(x:TicketListing){setSelected(x);setStudentSold(x.can_split?"0":String(x.remaining_student_seats??x.student_seats));setGuestSold(x.can_split?"0":String(x.remaining_guest_seats??x.guest_seats));}
  async function complete(){if(!selected)return;try{setBusy(true);await completePrivateListingSale(selected.id,Number(studentSold)||0,Number(guestSold)||0);setSelected(null);await refresh();Alert.alert(text("Transaction recorded","交易已记录"),selected.can_split?text("Remaining inventory has been updated.","剩余票数已经更新。") : text("The listing has been closed.","帖子已经关闭。"));}catch(e:any){Alert.alert(text("Could not complete","无法完成"),e.message);}finally{setBusy(false)}}
  async function remove(x:TicketListing){const message=text("Withdraw this listing? It will disappear from buyer search immediately.","确定撤下此帖子吗？它会立即从买家页面消失。");const confirmed=Platform.OS==="web"?globalThis.confirm(message):true;if(!confirmed)return;if(Platform.OS!=="web"){Alert.alert(text("Withdraw listing?","撤下帖子？"),message,[{text:text("Cancel","取消"),style:"cancel"},{text:text("Withdraw","撤下"),style:"destructive",onPress:()=>void doRemove(x.id)}]);return;}await doRemove(x.id)}
  async function doRemove(id:string){try{setBusy(true);await withdrawMyListingSafely(id);await refresh();}catch(e:any){Alert.alert(text("Cannot withdraw listing","无法撤下帖子"),e.message);}finally{setBusy(false)}}

  return <ScrollView style={s.page} contentContainerStyle={s.content}><View style={s.pageActions}><Pressable style={s.home} onPress={()=>router.replace(Platform.OS==="web"?"/marketplace":"/")}><Ionicons name="home-outline" size={18} color={C.navy}/><Text style={s.homeText}>{text("Home","返回主页")}</Text></Pressable><Pressable style={s.home} onPress={()=>router.push("/my-profile")}><Ionicons name="person-outline" size={18} color={C.navy}/><Text style={s.homeText}>{text("My profile","我的资料")}</Text></Pressable></View><Text style={s.title}>{text("My listings","我的帖子")}</Text><Text style={s.subtitle}>{text("Manage your Formal, journey and event tickets. You can record a completed sale or withdraw any active post.","管理你的 Formal、车票和活动票帖子。你可以记录已完成的交易，或随时撤下仍在展示的帖子。")}</Text>{items.length===0?<View style={s.empty}><Text style={s.emptyText}>{text("You have no listings.","你还没有发布帖子。")}</Text></View>:items.map(x=>{const student=x.remaining_student_seats??x.student_seats,guest=x.remaining_guest_seats??x.guest_seats,isFormal=(x.listing_category??"formal")==="formal";return <View key={x.id} style={s.card}><View style={s.head}><View style={{flex:1}}><Text style={s.cardTitle} numberOfLines={2}>{localValue(x.ticket_type??x.formal_type,language)} · {x.campus??x.colleges.university}</Text><Text style={s.meta}>{x.formal_date} · {String(x.formal_time).slice(0,5)} · {localValue(x.status,language)}</Text></View><View style={s.badge}><Text style={s.badgeText}>{x.open_to_swap?text("Open to swaps","愿意换票"):text("Direct contact","直接联系")}</Text></View></View>{x.listing_category==="coach_train"&&<Text style={s.inventory}>{x.origin_name} → {x.destination_name} · {text("arrives","到达")} {x.arrival_date??x.formal_date} {String(x.arrival_time??"").slice(0,5)} · {formatDuration(x.duration_minutes,language)}</Text>}<Text style={s.inventory}>{text("Remaining","剩余")}: {student} {isFormal?text(`student/member · ${guest} guest`,`本院成员 · ${guest} 位宾客`):text("ticket(s)","张票")}</Text><View style={s.actions}><Pressable style={s.view} onPress={()=>router.push(`/listing-detail?id=${x.id}`)}><Text style={s.viewText}>{text("View post","查看帖子")}</Text></Pressable>{x.status==="active"&&<Pressable style={s.primary} onPress={()=>openComplete(x)}><Text style={s.primaryText}>{text("Confirm transaction completed","确认交易完成")}</Text></Pressable>}<Pressable style={s.outline} disabled={busy} onPress={()=>remove(x)}><Text style={s.outlineText}>{text("Withdraw listing","撤下帖子")}</Text></Pressable></View></View>})}
    <Modal visible={!!selected} transparent animationType="fade" onRequestClose={()=>setSelected(null)}><View style={s.overlay}><View style={s.modal}><Text style={s.modalTitle}>{selected?.can_split?text("How many tickets were sold?","卖出了几张票？"):text("Complete this transaction?","确认完成交易？")}</Text><Text style={s.modalText}>{selected?.can_split?text("The listing remains active while tickets are left.","如仍有余票，帖子会继续展示。") : text("This listing cannot be split. Confirming closes the entire listing.","此帖子不可拆分出售，确认后会关闭整个帖子。")}</Text>{selected?.can_split&&<View style={s.qtyRow}><Qty label={text(`Student/member · max ${selected.remaining_student_seats??selected.student_seats}`,`本院成员 · 最多 ${selected.remaining_student_seats??selected.student_seats}`)} value={studentSold} set={setStudentSold}/><Qty label={text(`Guest · max ${selected.remaining_guest_seats??selected.guest_seats}`,`宾客 · 最多 ${selected.remaining_guest_seats??selected.guest_seats}`)} value={guestSold} set={setGuestSold}/></View>}<View style={s.modalActions}><Pressable style={s.cancel} onPress={()=>setSelected(null)}><Text style={s.cancelText}>{text("Cancel","取消")}</Text></Pressable><Pressable style={s.primary} disabled={busy} onPress={complete}><Text style={s.primaryText}>{busy?text("Saving...","正在保存……"):text("Confirm completed","确认完成")}</Text></Pressable></View></View></View></Modal>
  </ScrollView>;
}
function Qty({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <View style={{flex:1}}><Text style={s.label}>{label}</Text><TextInput style={s.input} keyboardType="numeric" value={value} onChangeText={set}/></View>}
function formatDuration(minutes:number|null|undefined,language:"en"|"zh"){if(!minutes)return language==="zh"?"未填写时长":"duration not stated";const h=Math.floor(minutes/60),m=minutes%60;return language==="zh"?`${h} 小时${m?` ${m} 分钟`:""}`:`${h} hr${h===1?"":"s"}${m?` ${m} min`:""}`;}
function localValue(value:string|null|undefined,language:"en"|"zh"){if(!value)return "";if(language==="en")return value;return ({active:"展示中",sold_out:"已售完",withdrawn:"已撤下",expired:"已过期",Formal:"Formal",Coach:"大巴",Train:"火车","Other event":"其他活动",Event:"活动"} as Record<string,string>)[value]??value;}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg},content:{maxWidth:900,width:"100%",alignSelf:"center",padding:24,paddingTop:30,paddingBottom:70},pageActions:{flexDirection:"row",gap:8,flexWrap:"wrap",marginBottom:18},home:{flexDirection:"row",alignItems:"center",gap:7,minHeight:42,borderRadius:14,borderWidth:1,borderColor:C.border,backgroundColor:"#fff",paddingHorizontal:13},homeText:{color:C.navy,fontWeight:"900"},title:{fontSize:34,fontWeight:"900",color:C.navy},subtitle:{marginTop:8,color:C.muted,lineHeight:22},empty:{marginTop:20,backgroundColor:C.card,borderWidth:1,borderColor:C.border,borderRadius:26,padding:30,alignItems:"center"},emptyText:{color:C.muted,fontWeight:"800"},card:{marginTop:16,backgroundColor:C.card,borderWidth:1,borderColor:C.border,borderRadius:26,padding:20},head:{flexDirection:"row",gap:12},cardTitle:{fontSize:19,fontWeight:"900",color:C.navy},meta:{marginTop:6,color:C.muted,fontWeight:"700"},badge:{backgroundColor:"#EEF2FF",borderRadius:999,paddingHorizontal:10,paddingVertical:7},protected:{backgroundColor:C.okBg},badgeText:{color:C.navy,fontSize:12,fontWeight:"900"},inventory:{marginTop:12,color:C.navy,fontWeight:"900"},auto:{marginTop:10,backgroundColor:C.okBg,color:C.ok,padding:12,borderRadius:14,lineHeight:20,fontWeight:"700"},actions:{flexDirection:"row",gap:10,marginTop:16,flexWrap:"wrap"},view:{minHeight:50,borderRadius:16,borderWidth:1,borderColor:C.navy,paddingHorizontal:16,alignItems:"center",justifyContent:"center"},viewText:{color:C.navy,fontWeight:"900"},primary:{flex:1,minWidth:210,minHeight:50,borderRadius:16,backgroundColor:C.navy,alignItems:"center",justifyContent:"center",paddingHorizontal:14},primaryText:{color:"#fff",fontWeight:"900"},outline:{minHeight:50,borderRadius:16,borderWidth:1,borderColor:C.border,paddingHorizontal:16,alignItems:"center",justifyContent:"center"},outlineText:{color:C.danger,fontWeight:"900"},overlay:{flex:1,backgroundColor:"rgba(7,27,58,.45)",alignItems:"center",justifyContent:"center",padding:24},modal:{width:"100%",maxWidth:560,backgroundColor:C.card,borderRadius:26,padding:22},modalTitle:{fontSize:23,fontWeight:"900",color:C.navy},modalText:{marginTop:8,color:C.muted,lineHeight:21},qtyRow:{flexDirection:"row",gap:12,marginTop:15},label:{color:C.muted,fontSize:13,fontWeight:"900",marginBottom:8},input:{height:52,borderWidth:1,borderColor:C.border,borderRadius:15,paddingHorizontal:14},modalActions:{flexDirection:"row",gap:10,marginTop:20},cancel:{minHeight:50,borderWidth:1,borderColor:C.border,borderRadius:16,paddingHorizontal:18,alignItems:"center",justifyContent:"center"},cancelText:{color:C.navy,fontWeight:"900"}});
